  main = ".open-next/worker.js"
  name = "haunted-halloween-landing"
  compatibility_date = "2025-10-24"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
